Name: 'Sane PR Line Limiter'
description: 'Warn about large pull requests'

inputs:
  lines:
    description: warn if pull request has more than this number of lines
    default: 50
  branch:
    description: main or master
    default: main

runs:
  using: 'composite'
  steps:
    - name: Counting lines in diff
      shell: bash
      run: curl -H "Accept: application/vnd.github.v3.diff" https://${{ github.token }}:x-oauth-basic@api.github.com/repos/${{ github.repository}}/pulls/1
