Name: 'Sane PR Line Limiter'
description: 'Warn about large pull requests'

inputs:
  lines:
    description: warn if pull request has more than this number of lines
    default: 50
  branch:
    description: main or master
    default: main

runs:
  using: 'composite'
  steps:
    - name: Counting lines in diff
      shell: bash
      run: git clone https://${{ github.token }}@github.com/${{ github.repository }}/$GITHUB_BASE_REF . && git diff $GITHUB_SHA

